[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "elf2uf2-rs --deploy --serial"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"

WIFI_NETWORK = "SSID"
WIFI_PASSWD = "PASSWORD"
SLACK_ID = "SLACK_ID"
API_TOKEN = "UUID"
